Description of gen2PNwaveform
gen2PNwaveform
PURPOSE
Creates and Returns normalized phase vector of waveform in the Fourier Domain
SYNOPSIS
function wave = gen2PNwaveform(fpos, ta, phase, fmin, fmax,m1, m2,datalen,initial_phase,snr,N,avec, normfac)
DESCRIPTION
Creates and Returns normalized phase vector of waveform in the Fourier Domain
General expression for a 2PN waveform in a fourier domain is
 W(f) = A(f)exp(-iPsi(f)), this function returns exp(-iPsi(f))
 Waveform generation happens through component mass values m1, m2
CROSS-REFERENCE INFORMATION
This function calls:
waveform Function to create Restricted 2PN Waveform in Fourier Domain
This function is called by:
crcbgwpso_mass Regression of 2PNWaveform using Mass Space PSO
mfgw_mass MatchedFiltering for Mass space PSO