Description of gen2PNwaveform_tau
gen2PNwaveform_tau
PURPOSE
Returns normalized phase vector of waveform in the Fourier Domain
SYNOPSIS
function wave = gen2PNwaveform_tau(fpos, ta, phase, fmin, fmax,tau0, tau1p5,datalen,initial_phase,snr,N, avec, normfac)
DESCRIPTION
Returns normalized phase vector of waveform in the Fourier Domain
CROSS-REFERENCE INFORMATION
This function calls:
waveform_tau Function to create Restricted 2PN Waveform in Fourier Domain
This function is called by:
crcbgwpso_tau Regression of 2PNWaveform using Chirp-Time Space PSO
mfgw_tau MatchedFiltering for Chirp time space PSO