Description of rungwpso
rungwpso
PURPOSE
Script to run Chirp-time or Mass Space PSO on a user specified datafile and PSD.
SYNOPSIS
function []=rungwpso(filename)
DESCRIPTION
Script to run Chirp-time or Mass Space PSO on a user specified datafile and PSD.
Refer to User Manual for usage
CROSS-REFERENCE INFORMATION
This function calls:
boundary_plot Creates and returns a Boundary Plot as a figure in the Chirp-time (Tau1.5 and Tau0) space
crcbgwpso_mass Regression of 2PNWaveform using Mass Space PSO
crcbgwpso_tau Regression of 2PNWaveform using Chirp-Time Space PSO
mfgw_mass MatchedFiltering for Mass space PSO
mfgw_tau MatchedFiltering for Chirp time space PSO
preprocessing PREPROCESSING Function to create vectors used for waveform generation
This function is called by: