Description of crcbgwpso_mass
crcbgwpso_mass
PURPOSE
Regression of 2PNWaveform using Mass Space PSO
SYNOPSIS
function outResults = crcbgwpso_mass(inParams,psoParams,nRuns, sampling_freq)
DESCRIPTION
Regression of 2PNWaveform using Mass Space PSO
 Input: inParams: Struct containing data and signal parameters
        psoParams: Struct containing PSO parameters
        nRuns: Number of PSO iterations
        sampling_freq: Sampling Frequency of data
 Output: outResults: Struct containing the following parameters
 'allRunsOutput': An N element struct array containing results from each PSO
              run. The fields of this struct are:
                 'fitVal': The fitness value.
                 'qcCoefs': The coefficients [m1, m2].
                 'estSig': The estimated signal.
                 'totalFuncEvals': The total number of fitness
                                   evaluations.
 'bestRun': The best run.
 'bestFitness': best fitness from the best run.
 'bestSig' : The signal estimated in the best run.
 'bestQcCoefs' : [m1, m2] found in the best run.
CROSS-REFERENCE INFORMATION
This function calls:
gen2PNwaveform Creates and Returns normalized phase vector of waveform in the Fourier Domain
innerprodpsd Calculates the inner product of vectors X and Y for the case of Gaussian
psofitfunc Fitness function for Mass Space PSO
This function is called by:
rungwpso Script to run Chirp-time or Mass Space PSO on a user specified datafile and PSD.