Description of mfgw_mass
mfgw_mass
PURPOSE
MatchedFiltering for Mass space PSO
SYNOPSIS
function [mfVal, max_arg] = mfgw_mass(x,params)
DESCRIPTION
MatchedFiltering for Mass space PSO
Generates a combined matched-filtering timeseries from both quadrature templates and
returns index and value of the maximum of this series,
Input: x = [m1, m2], vector containing mass parameters for
           creating quadrature templates
       params: Struct containing signal parameters
Output: mfVal: Maximum value of total matchedfiltering timeseries
        max_arg: Index of maximum value
CROSS-REFERENCE INFORMATION
This function calls:
gen2PNwaveform Creates and Returns normalized phase vector of waveform in the Fourier Domain
matchedfiltering Function to perform FFT correlation based matched filtering
This function is called by:
psofitfunc Fitness function for Mass Space PSO
rungwpso Script to run Chirp-time or Mass Space PSO on a user specified datafile and PSD.